queue_params:
  queue_addr: "127.0.0.1:6379"
  queue_pass: ""
  queue_num: 0
  queue_protocol: 2
db_params:
  host: localhost
  user: user
  password: pass
  name: cimrique_pgdb
  port: 5432
server_params:
  server_address: http://127.0.0.1:3200
  listen_port: ":3200"
  rate_limit_max: 10000
  rate_limit_expiration_seconds: 60
microservice_params:
  queue_server_address: http://127.0.0.1:3400
  queue_listen_port: ":3400"
