db_params:
  host: localhost
  user: user
  password: pass
  name: cimrique_pgdb
  port: 5432
server_params:
  server_address: http://127.0.0.1:3000
  listen_port: ":3000"
  rate_limit_max: 10000
  rate_limit_expiration_seconds: 60